[platformio]
default_envs = 
	rak3112
boards_dir = rakwireless/boards

[common]
build_flags = 
	-D SW_VERSION_1=1     ; major version increase on API change / not backwards compatible
	-D SW_VERSION_2=0     ; minor version increase on API change / backward compatible
	-D SW_VERSION_3=11    ; patch version increase on bugfix, no affect on API
	-D LIB_DEBUG=0        ; 0 Disable LoRaWAN debug output
	-D API_DEBUG=0        ; 0 Disable WisBlock API debug output
	-D BASE_BOARD=0       ; 1 = RAK19003 0 = other base boards
	-DMYLOG_LOG_LEVEL=MYLOG_LOG_LEVEL_DEBUG
monitor_speed = 115200
lib_deps = 
	beegee-tokyo/SX126x-Arduino
	https://github.com/Makuna/NeoPixelBus.git
	https://github.com/h2zero/NimBLE-Arduino.git
	ArduinoJson


[env:rak3112]
platform = espressif32
board = rak3112
framework = arduino
board_build.partitions = huge_app.csv
build_flags = 
	${common.build_flags}
	-I rakwireless/variants/rak3112
	-D _VARIANT_RAK3112_=1
	-DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
	-D NO_BLE_LED=1
	-D MY_DEBUG=1     ; 0 Disable application debug output
lib_deps = 
	${common.lib_deps}
